
package fact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "factorial", targetNamespace = "http://fact/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Factorial {


    /**
     * 
     * @param n
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "factorial", targetNamespace = "http://fact/", className = "fact.Factorial_Type")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://fact/", className = "fact.FactorialResponse")
    @Action(input = "http://fact/factorial/factorialRequest", output = "http://fact/factorial/factorialResponse")
    public int factorial(
        @WebParam(name = "n", targetNamespace = "")
        int n);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://fact/", className = "fact.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://fact/", className = "fact.HelloResponse")
    @Action(input = "http://fact/factorial/helloRequest", output = "http://fact/factorial/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
